name: CI Workflow
   
on:
  push:
    branches: [ branch** ]   
  pull_request:
    branches:
     - main
     - develop
     

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Checkout dev branch from GitHub
        uses: actions/checkout@v2
       
      - name: Step 2 - Gradle wrapper version validation
        uses: gradle/wrapper-validation-action@v1
      
      - name: Step 3 - Use Java version 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
          cache: gradle
                
      - name: chmod permissions
        run: chmod +x ./gradlew
                  
      - name: Step4 - Build with Gradle
        uses: gradle/gradle-build-action@v2.1.1
        with:
          arguments: build
          
      - name: Step 5 - Listing the build file name
        run: |
          ls '${{ github.workspace }}'/build/libs
