name: CI Workflow
   
on:
  push:
    branches:
      - master
      - develop

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Checkout dev branch from GitHub
        uses: actions/checkout@v2
       
      - name: Step 2 - Gradle wrapper version validation
        uses: gradle/wrapper-validation-action@v1
        
      -  name: step3 printing name
         run: |
           echo "this is feature"
      
      
